version: '3'

services:
  web:
    restart: always
    build: /web/
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command:  bash -c  python manage.py runserver 0.0.0.0:8000


  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80" 
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

 

volumes:
  web-django:
  web-static:
  pgdata: